### ISSUE TITLE
OSS Not working

### ISSUE THREAD

**Issue by tharun143** [Catalyst-IN/Open-Source-Events#19]
It seems Open Source Software competition is not happening. There are some discrepancies in the timeline.  See the below image for better understanding.
![Screenshot (152)](https://user-images.githubusercontent.com/41537996/82110361-60cbab80-975b-11ea-8ace-1bfb022e3ebb.png)

**Comment by anubhavsingh16** [comment]
Email: contest@oss.kr ask this question from OSS
