### ISSUE TITLE
ESA link broken

### ISSUE THREAD

**Issue by tharun143** [Catalyst-IN/Open-Source-Events#20]
I am not able to open the ESA link

**Comment by anubhavsingh16** [comment]
Ok thanks for informing us

**Comment by anubhavsingh16** [comment]
@tharun143 can you work on this issue?

**Comment by tharun143** [comment]
What do you mean by working? and now we are in July and I think it doesn't work even if we update the link. Like it's already expired. So no use of updating the link.

**Comment by anubhavsingh16** [comment]
🧐 For next year students.

**Comment by anubhavsingh16** [comment]
Just updated
