### ISSUE TITLE
Adding more events to the list!

### ISSUE THREAD

**Issue by garimasingh128** [Catalyst-IN/Open-Source-Events#26]
[Google season of docs](https://www.jenkins.io/sigs/docs/gsod/)- Takes palce in June
[Jenkins UI-UX Hackfest](https://github.com/jenkinsci/ui-ux-hackfest-2020/tree/master/presentations)- Takes place in May

**Comment by anubhavsingh16** [comment]
Thank You @garimasingh128

**Comment by ivaibhavjindal** [comment]
Can you please add [Psoc](http://pclubsummerofcode.in) as well?

**Comment by garimasingh128** [comment]
Do I need to add it in the README only?

**Comment by anubhavsingh16** [comment]
if you like to add in the website then https://github.com/Catalyst-IN/OpenSourceEvents-Frontend this is the repo for the website.

**Comment by anubhavsingh16** [comment]
Both done @garimasingh128

**Comment by anubhavsingh16** [comment]
Thank You :p
