### ISSUE TITLE
Add SLoP (Semester Long Project)

### ISSUE THREAD

**Issue by vybhav72954** [Catalyst-IN/Open-Source-Events#35]
> Semester Long Projects or SLoP is an initiative by the Developer Student Club (DA-IICT), exclusively for students who are new to open source software development to get started with open source contributions.
> 
> We want to increase the development culture and involvement of students with open-source technologies which will present the benefits of open source as well as introduce them to the cutting edge tech and coding practices.

Can you assign me the issue, so that I can start a PR.

Moreover, considering you are participating in ```Hacktoberfest``` you need to include it in Topics [Read this](https://github.com/digitalocean/hacktoberfest/pull/596)

**Comment by anubhavsingh16** [comment]
![Open Source   Hackathons](https://user-images.githubusercontent.com/47811606/131302378-02493379-4225-4010-b7bc-ca261f9916df.gif)
